### ISSUE TITLE
Contributing .md

### ISSUE THREAD

**Issue by jycr753** [sp90/platform-boilerplate#1]
Will be there an contributing file that will points out:

naming convention
format
and so on...

**Comment by sp90** [comment]
@jycr753 Yes of course its needed to keep a sticked and well written repo

**Comment by sp90** [comment]
Your open to write such file:

I would prefer if we used john papa's guide for angular formating and bem for css classes naming conventions.

Besides that i dont have any requests.

**Comment by jycr753** [comment]
Great :+1:

**Comment by jycr753** [comment]
I will added the documentation assuming there will be a dev branch and master

**Comment by sp90** [comment]
Thats great :+1:
